<script language="javascript" src="<?php echo $baseDir; ?>/www/js/jquery.js"></script>
<script language="javascript" src="<?php echo $baseDir; ?>/www/js/bootstrap.min.js"></script>
<script language="javascript" src="<?php echo $baseDir; ?>/www/js/global.js"></script>
<link href="<?php echo $baseDir; ?>/www/css/bootstrap.css" media="screen" rel="stylesheet" type="text/css">
<link href="<?php echo $baseDir; ?>/www/css/global.css" media="screen" rel="stylesheet" type="text/css">
<link type="text/css" href="<?php echo $baseDir; ?>/www/css/style.css" rel="stylesheet" />
<link type="text/css" href="<?php echo $baseDir; ?>/www/css/jquery.jgrowl.css" rel="stylesheet" />
<script src="<?php echo $baseDir; ?>/www/js/custom.js"></script>
<script src="<?php echo $baseDir; ?>/www/js/jquery.jgrowl_minimized.js"></script>

<script type="text/javascript" src="<?=$baseDir?>/www/js/swfupload.js"></script>
<script type="text/javascript" src="<?=$baseDir?>/www/js/swfupload.queue.js"></script>
<script type="text/javascript" src="<?=$baseDir?>/www/js/fileprogress.js"></script>
<script type="text/javascript" src="<?=$baseDir?>/www/js/handlers.js"></script>